version: '3.8'
services: 
  backend:
    build: ./backend
    ports:
      - '3333:3333'
    volumes:
      - /app/node_modules
      # - logs:/app/logs
    # Acesso MONGODB
    env_file:
      - ./env/mongo.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile_dev
    ports:
      - '80:80'
    volumes:
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend





